name: 'GSA/grace-decider'
description: 'Program to monitor status of an IaaC provisioning request for GRACE PaaS'
license: cc0-1.0
openSourceProject: 1
governmentWideReuseProject: 1
tags:
    - open-source
    - opensource
    - grace
    - devsecops
    - grace-paas
contact:
    email: grace-staff@gsa.gov
